
settings:
  commit_msg: "docs: update README.ca.md with latest GitHub activity"
  readme_file: "./README.ca.md"
messages:
  comments: "ğŸ’¬ Ha comentat a {ID} a {REPO}"
  issue_opened: "â—ï¸ Ha obert el tema {ID} a {REPO}"
  issue_closed: "âœ”ï¸ Ha tancat el tema {ID} a {REPO}"
  pr_opened: "ğŸ’ª Ha obert una PR {ID} a {REPO}"
  pr_closed: "âŒ Ha tancat una PR {ID} a {REPO}"
  pr_merged: "ğŸ‰ Ha fusionat una PR {ID} a {REPO}"
  create_repo: "ğŸ“” Ha creat un nou repositori {REPO}"
  fork_repo: "ğŸ”± Ha bifurcat {FORK} from {REPO}"
  wiki_create: "ğŸ“– Ha creat una nova wiki {WIKI} a {REPO}"
  added_member: "ğŸ¤ S'ha convertit en colÂ·laborador a {REPO}"
  changes_approved: "ğŸ‘ Ha aprovat {ID} a {REPO}"
  changes_requested: "ğŸ”´ Ha demanat canvis a {ID} a {REPO}"
  new_release: "âœŒï¸ Ha llanÃ§at {ID} a {REPO}"
  new_star: "â­ Ha destacat {REPO}"
  push: "â¬†ï¸ Ha empÃ¨s {AMOUNT} commit(s) a {REPO}"
