settings:
  commit_msg: "docs: update README.es.md with latest GitHub activity"
  readme_file: "./README.es.md"
messages:
  comments: "ğŸ’¬ Ha comentado a {ID} en {REPO}"
  issue_opened: "â—ï¸ Ha abierto el tema {ID} en {REPO}"
  issue_closed: "âœ”ï¸ Ha cerrado el tema {ID} en {REPO}"
  pr_opened: "ğŸ’ª Ha abierto una PR {ID} en {REPO}"
  pr_closed: "âŒ Ha cerrado una PR {ID} en {REPO}"
  pr_merged: "ğŸ‰ Ha fusionado una PR {ID} en {REPO}"
  create_repo: "ğŸ“” Ha creado un nuevo repositorio {REPO}"
  fork_repo: "ğŸ”± Ha bifurcado {FORK} desde {REPO}"
  wiki_create: "ğŸ“– Ha creado una nueva wiki {WIKI} en {REPO}"
  added_member: "ğŸ¤ Se ha convertido en colaborador de {REPO}"
  changes_approved: "ğŸ‘ Ha aprobado {ID} en {REPO}"
  changes_requested: "ğŸ”´ Ha pedido cambios a {ID} en {REPO}"
  new_release: "âœŒï¸ Ha publicado {ID} en {REPO}"
  new_star: "â­ Ha destacado {REPO}"
  push: "â¬†ï¸ Ha empujado {AMOUNT} compromis(os) en {REPO}"
