settings:
  commit_msg: "docs: update README.it.md with latest GitHub activity"
  readme_file: "./README.it.md"
date:
  timezone: "Europe/Madrid"
messages:
  comments: "ğŸ’¬ Ha commentato {ID} in {REPO}"
  issue_opened: "â—Ha aperto il tema {ID} in {REPO}"
  issue_closed: "âœ”ï¸Ha chiuso il tema {ID} in {REPO}"
  pr_opened: "ğŸ’ª Ha aperto il PR {ID} in {REPO}"
  pr_closed: "âŒ Ha chiuso il PR {ID} in {REPO}"
  pr_merged: "ğŸ‰ Ha unificato il PR {ID} in {REPO}"
  create_repo: "ğŸ“” Ha creato un nuovo repository {REPO}"
  fork_repo: "ğŸ”± Ha biforcato {FORK} da {REPO}"
  wiki_create: "ğŸ“– Ha creato una nuova pagina wiki {WIKI} in {REPO}"
  added_member: "ğŸ¤ Ãˆ un collaboratore di {REPO}"
  changes_approved: "ğŸ‘ Ha approvato {ID} in {REPO}"
  changes_requested: "ğŸ”´ Ha richiesto dei cambi in {ID} in {REPO}"
  new_release: "âœŒï¸ Ha publicato {ID} in {REPO}"
  new_star: "â­ Ha rimarcato {REPO}"
  push: "â¬†ï¸ Ha impulsato {AMOUNT} commit(s) in {REPO}"
