name: GitHub Star Tracker
on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:
permissions:
  contents: write
jobs:
  track-stars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Track star changes
        id: tracker
        uses: fbuireu/github-star-tracker@v1
        with:
          github-token: ${{ secrets.PAT }}
          locale: en
          include-charts: true
          visibility: owned         
          include-forks: false       
          include-archived: false    
          track-stargazers: true      
          notification-threshold: auto          
      - name: Send email report
        #if: steps.tracker.outputs.stars-changed == 'true'
        uses: dawidd6/action-send-mail@v9
        with:
          server_address: ${{ vars.SMTP_SERVER }}
          server_port: ${{ vars.SMTP_PORT }}
          username: ${{ vars.MAIL_USERNAME }} 
          password: ${{ secrets.MAIL_PASSWORD }} 
          subject: '⭐ Star Tracker: ${{ steps.tracker.outputs.total-stars }} stars (GitHub Action) ⭐'
          html_body: ${{ steps.tracker.outputs.report-html }}
          to: ${{ vars.MAIL_USERNAME }} 
          from: GitHub Star Tracker
